# Generated by Django 4.0.1 on 2022-07-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_song_avatar_song_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='img',
        ),
    ]
