# Generated by Django 4.0.1 on 2022-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_thumb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
