# Generated by Django 4.0.1 on 2022-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_thumb_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='thumb',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
