# Generated by Django 4.0.1 on 2022-07-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_thumb_remove_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
